name: icat-test
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - appdirs=1.4.3=py_1
  - asn1crypto=0.24.0=py37_1003
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - blosc=1.16.3=he1b5a44_1
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.6.16=hecc5488_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - configargparse=0.13.0=py_1
  - cryptography=2.7=py37h72c5cf5_0
  - cycler=0.10.0=py_1
  - datrie=0.7.1=py37h14c3975_0
  - decorator=4.4.0=py_0
  - docutils=0.14=py37_1001
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - gitdb2=2.0.5=py_0
  - gitpython=2.1.11=py_0
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py37_1000
  - igraph=0.7.1=h2166141_1005
  - intel-openmp=2019.4=243
  - ipython=7.6.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.14.1=py37_0
  - joblib=0.13.2=py_0
  - jsonschema=3.0.1=py37_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - libblas=3.8.0=5_h6e990d7_netlib
  - libcblas=3.8.0=5_h6e990d7_netlib
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=5_h6e990d7_netlib
  - libpng=1.6.37=hed695b0_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_1
  - llvmlite=0.28.0=py37hdbcaa40_0
  - louvain=0.6.1=py37hf484d3e_2
  - lzo=2.10=h14c3975_1000
  - matplotlib-base=3.1.1=py37hfd891ef_0
  - mkl=2018.0.3=1
  - mock=3.0.5=py37_0
  - ncurses=6.1=hf484d3e_1002
  - numba=0.43.1=py37hf2d7682_0
  - numexpr=2.6.9=py37h637b7d7_1000
  - numpy=1.16.3=py37he5ce36f_0
  - numpy-base=1.15.0=py37h1793315_0
  - openssl=1.1.1c=h516909a_0
  - pandas=0.24.2=py37hb3f55d8_0
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.1.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - pomegranate=0.11.0=py37h9de70de_0
  - prompt_toolkit=2.0.9=py_0
  - psutil=5.6.3=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycairo=1.18.1=py37h438ddbb_0
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyrsistent=0.15.3=py37h516909a_0
  - pysocks=1.7.0=py37_0
  - pytables=3.5.1=py37h442f067_1
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.0=py_0
  - python-igraph=0.7.1.post7=py37h516909a_0
  - pytz=2019.1=py_0
  - pyyaml=5.1.1=py37h516909a_0
  - ratelimiter=1.2.0=py37_1000
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - scikit-learn=0.21.1=py37h627018c_0
  - scipy=1.2.1=py37h09a28d5_1
  - seaborn=0.9.0=py_1
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_1000
  - smmap2=2.0.5=py_0
  - snakemake-minimal=5.4.5=py_0
  - sqlite=3.29.0=hcee41ef_0
  - statsmodels=0.9.0=py37h3010b51_1000
  - tk=8.6.9=hed695b0_1002
  - tornado=6.0.3=py37h516909a_0
  - traitlets=4.3.2=py37_1000
  - urllib3=1.25.3=py37_0
  - wcwidth=0.1.7=py_1
  - wheel=0.33.4=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zlib=1.2.11=h516909a_1005
  - pip:
    - anndata==0.6.19
    - colorcet==2.0.1
    - h5py==2.9.0
    - natsort==6.0.0
    - networkx==1.11
    - param==1.9.1
    - pyct==0.4.6
    - scanpy==1.4.3
    - tqdm==4.32.1
    - umap-learn==0.3.8
prefix: /home/dakota/anaconda3/envs/icat-test

